/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdmRouteRouteImport } from './routes/adm/route'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as FornecedorRouteRouteImport } from './routes/fornecedor/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AuthenticatedAssinaturaRouteImport } from './routes/_authenticated/assinatura'
import { Route as AuthenticatedComprarRouteImport } from './routes/_authenticated/comprar'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedConsultorRouteImport } from './routes/_authenticated/consultor'
import { Route as AuthenticatedConversasRouteImport } from './routes/_authenticated/conversas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedFornecedoresRouteImport } from './routes/_authenticated/fornecedores'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPdvRouteImport } from './routes/_authenticated/pdv'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AdmIndexRouteImport } from './routes/adm/index'
import { Route as AdmAuditoriaRouteImport } from './routes/adm/auditoria'
import { Route as AdmClientesRouteImport } from './routes/adm/clientes'
import { Route as AdmCobrancaRouteImport } from './routes/adm/cobranca'
import { Route as AdmEquipeRouteImport } from './routes/adm/equipe'
import { Route as AdmLoginRouteImport } from './routes/adm/login'
import { Route as ApiCaktoWebhookRouteImport } from './routes/api.cakto-webhook'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as FornecedorIndexRouteImport } from './routes/fornecedor/index'
import { Route as FornecedorCatalogoRouteImport } from './routes/fornecedor/catalogo'
import { Route as FornecedorConversasRouteImport } from './routes/fornecedor/conversas'
import { Route as FornecedorPedidosRouteImport } from './routes/fornecedor/pedidos'
import { Route as FornecedorVitrineRouteImport } from './routes/fornecedor/vitrine'
import { Route as AdmClienteIdRouteImport } from './routes/adm/cliente.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmRouteRoute = AdmRouteRouteImport.update({
  id: '/adm',
  path: '/adm',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorRouteRoute = FornecedorRouteRouteImport.update({
  id: '/fornecedor',
  path: '/fornecedor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAssinaturaRoute = AuthenticatedAssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprarRoute = AuthenticatedComprarRouteImport.update({
  id: '/comprar',
  path: '/comprar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsultorRoute = AuthenticatedConsultorRouteImport.update({
  id: '/consultor',
  path: '/consultor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConversasRoute = AuthenticatedConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFornecedoresRoute =
  AuthenticatedFornecedoresRouteImport.update({
    id: '/fornecedores',
    path: '/fornecedores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPdvRoute = AuthenticatedPdvRouteImport.update({
  id: '/pdv',
  path: '/pdv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdmIndexRoute = AdmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdmRouteRoute,
} as any)
const AdmAuditoriaRoute = AdmAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdmRouteRoute,
} as any)
const AdmClientesRoute = AdmClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdmRouteRoute,
} as any)
const AdmCobrancaRoute = AdmCobrancaRouteImport.update({
  id: '/cobranca',
  path: '/cobranca',
  getParentRoute: () => AdmRouteRoute,
} as any)
const AdmEquipeRoute = AdmEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AdmRouteRoute,
} as any)
const AdmLoginRoute = AdmLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdmRouteRoute,
} as any)
const ApiCaktoWebhookRoute = ApiCaktoWebhookRouteImport.update({
  id: '/api/cakto-webhook',
  path: '/api/cakto-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const FornecedorIndexRoute = FornecedorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FornecedorRouteRoute,
} as any)
const FornecedorCatalogoRoute = FornecedorCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => FornecedorRouteRoute,
} as any)
const FornecedorConversasRoute = FornecedorConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => FornecedorRouteRoute,
} as any)
const FornecedorPedidosRoute = FornecedorPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => FornecedorRouteRoute,
} as any)
const FornecedorVitrineRoute = FornecedorVitrineRouteImport.update({
  id: '/vitrine',
  path: '/vitrine',
  getParentRoute: () => FornecedorRouteRoute,
} as any)
const AdmClienteIdRoute = AdmClienteIdRouteImport.update({
  id: '/cliente/$id',
  path: '/cliente/$id',
  getParentRoute: () => AdmRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adm': typeof AdmRouteRouteWithChildren
  '/fornecedor': typeof FornecedorRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/comprar': typeof AuthenticatedComprarRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/consultor': typeof AuthenticatedConsultorRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/adm/auditoria': typeof AdmAuditoriaRoute
  '/adm/clientes': typeof AdmClientesRoute
  '/adm/cobranca': typeof AdmCobrancaRoute
  '/adm/equipe': typeof AdmEquipeRoute
  '/adm/login': typeof AdmLoginRoute
  '/api/cakto-webhook': typeof ApiCaktoWebhookRoute
  '/api/health': typeof ApiHealthRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/fornecedor/catalogo': typeof FornecedorCatalogoRoute
  '/fornecedor/conversas': typeof FornecedorConversasRoute
  '/fornecedor/pedidos': typeof FornecedorPedidosRoute
  '/fornecedor/vitrine': typeof FornecedorVitrineRoute
  '/adm/': typeof AdmIndexRoute
  '/fornecedor/': typeof FornecedorIndexRoute
  '/adm/cliente/$id': typeof AdmClienteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/assinatura': typeof AuthenticatedAssinaturaRoute
  '/comprar': typeof AuthenticatedComprarRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/consultor': typeof AuthenticatedConsultorRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/pdv': typeof AuthenticatedPdvRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/adm/auditoria': typeof AdmAuditoriaRoute
  '/adm/clientes': typeof AdmClientesRoute
  '/adm/cobranca': typeof AdmCobrancaRoute
  '/adm/equipe': typeof AdmEquipeRoute
  '/adm/login': typeof AdmLoginRoute
  '/api/cakto-webhook': typeof ApiCaktoWebhookRoute
  '/api/health': typeof ApiHealthRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/fornecedor/catalogo': typeof FornecedorCatalogoRoute
  '/fornecedor/conversas': typeof FornecedorConversasRoute
  '/fornecedor/pedidos': typeof FornecedorPedidosRoute
  '/fornecedor/vitrine': typeof FornecedorVitrineRoute
  '/adm': typeof AdmIndexRoute
  '/fornecedor': typeof FornecedorIndexRoute
  '/adm/cliente/$id': typeof AdmClienteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/adm': typeof AdmRouteRouteWithChildren
  '/fornecedor': typeof FornecedorRouteRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/contato': typeof ContatoRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre': typeof SobreRoute
  '/termos': typeof TermosRoute
  '/_authenticated/assinatura': typeof AuthenticatedAssinaturaRoute
  '/_authenticated/comprar': typeof AuthenticatedComprarRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/consultor': typeof AuthenticatedConsultorRoute
  '/_authenticated/conversas': typeof AuthenticatedConversasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/fornecedores': typeof AuthenticatedFornecedoresRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/pdv': typeof AuthenticatedPdvRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/adm/auditoria': typeof AdmAuditoriaRoute
  '/adm/clientes': typeof AdmClientesRoute
  '/adm/cobranca': typeof AdmCobrancaRoute
  '/adm/equipe': typeof AdmEquipeRoute
  '/adm/login': typeof AdmLoginRoute
  '/api/cakto-webhook': typeof ApiCaktoWebhookRoute
  '/api/health': typeof ApiHealthRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/fornecedor/catalogo': typeof FornecedorCatalogoRoute
  '/fornecedor/conversas': typeof FornecedorConversasRoute
  '/fornecedor/pedidos': typeof FornecedorPedidosRoute
  '/fornecedor/vitrine': typeof FornecedorVitrineRoute
  '/adm/': typeof AdmIndexRoute
  '/fornecedor/': typeof FornecedorIndexRoute
  '/adm/cliente/$id': typeof AdmClienteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adm'
    | '/fornecedor'
    | '/cadastro'
    | '/contato'
    | '/login'
    | '/planos'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/sobre'
    | '/termos'
    | '/assinatura'
    | '/comprar'
    | '/configuracoes'
    | '/consultor'
    | '/conversas'
    | '/dashboard'
    | '/equipe'
    | '/fornecedores'
    | '/integracoes'
    | '/onboarding'
    | '/pdv'
    | '/pedidos'
    | '/produtos'
    | '/relatorios'
    | '/vendas'
    | '/adm/auditoria'
    | '/adm/clientes'
    | '/adm/cobranca'
    | '/adm/equipe'
    | '/adm/login'
    | '/api/cakto-webhook'
    | '/api/health'
    | '/convite/$token'
    | '/fornecedor/catalogo'
    | '/fornecedor/conversas'
    | '/fornecedor/pedidos'
    | '/fornecedor/vitrine'
    | '/adm/'
    | '/fornecedor/'
    | '/adm/cliente/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/contato'
    | '/login'
    | '/planos'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/sobre'
    | '/termos'
    | '/assinatura'
    | '/comprar'
    | '/configuracoes'
    | '/consultor'
    | '/conversas'
    | '/dashboard'
    | '/equipe'
    | '/fornecedores'
    | '/integracoes'
    | '/onboarding'
    | '/pdv'
    | '/pedidos'
    | '/produtos'
    | '/relatorios'
    | '/vendas'
    | '/adm/auditoria'
    | '/adm/clientes'
    | '/adm/cobranca'
    | '/adm/equipe'
    | '/adm/login'
    | '/api/cakto-webhook'
    | '/api/health'
    | '/convite/$token'
    | '/fornecedor/catalogo'
    | '/fornecedor/conversas'
    | '/fornecedor/pedidos'
    | '/fornecedor/vitrine'
    | '/adm'
    | '/fornecedor'
    | '/adm/cliente/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/adm'
    | '/fornecedor'
    | '/cadastro'
    | '/contato'
    | '/login'
    | '/planos'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/sobre'
    | '/termos'
    | '/_authenticated/assinatura'
    | '/_authenticated/comprar'
    | '/_authenticated/configuracoes'
    | '/_authenticated/consultor'
    | '/_authenticated/conversas'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipe'
    | '/_authenticated/fornecedores'
    | '/_authenticated/integracoes'
    | '/_authenticated/onboarding'
    | '/_authenticated/pdv'
    | '/_authenticated/pedidos'
    | '/_authenticated/produtos'
    | '/_authenticated/relatorios'
    | '/_authenticated/vendas'
    | '/adm/auditoria'
    | '/adm/clientes'
    | '/adm/cobranca'
    | '/adm/equipe'
    | '/adm/login'
    | '/api/cakto-webhook'
    | '/api/health'
    | '/convite/$token'
    | '/fornecedor/catalogo'
    | '/fornecedor/conversas'
    | '/fornecedor/pedidos'
    | '/fornecedor/vitrine'
    | '/adm/'
    | '/fornecedor/'
    | '/adm/cliente/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdmRouteRoute: typeof AdmRouteRouteWithChildren
  FornecedorRouteRoute: typeof FornecedorRouteRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  ContatoRoute: typeof ContatoRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SobreRoute: typeof SobreRoute
  TermosRoute: typeof TermosRoute
  ApiCaktoWebhookRoute: typeof ApiCaktoWebhookRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adm': {
      id: '/adm'
      path: '/adm'
      fullPath: '/adm'
      preLoaderRoute: typeof AdmRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor': {
      id: '/fornecedor'
      path: '/fornecedor'
      fullPath: '/fornecedor'
      preLoaderRoute: typeof FornecedorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/assinatura': {
      id: '/_authenticated/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AuthenticatedAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comprar': {
      id: '/_authenticated/comprar'
      path: '/comprar'
      fullPath: '/comprar'
      preLoaderRoute: typeof AuthenticatedComprarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultor': {
      id: '/_authenticated/consultor'
      path: '/consultor'
      fullPath: '/consultor'
      preLoaderRoute: typeof AuthenticatedConsultorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversas': {
      id: '/_authenticated/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof AuthenticatedConversasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores': {
      id: '/_authenticated/fornecedores'
      path: '/fornecedores'
      fullPath: '/fornecedores'
      preLoaderRoute: typeof AuthenticatedFornecedoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pdv': {
      id: '/_authenticated/pdv'
      path: '/pdv'
      fullPath: '/pdv'
      preLoaderRoute: typeof AuthenticatedPdvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/adm/': {
      id: '/adm/'
      path: '/'
      fullPath: '/adm/'
      preLoaderRoute: typeof AdmIndexRouteImport
      parentRoute: typeof AdmRouteRoute
    }
    '/adm/auditoria': {
      id: '/adm/auditoria'
      path: '/auditoria'
      fullPath: '/adm/auditoria'
      preLoaderRoute: typeof AdmAuditoriaRouteImport
      parentRoute: typeof AdmRouteRoute
    }
    '/adm/clientes': {
      id: '/adm/clientes'
      path: '/clientes'
      fullPath: '/adm/clientes'
      preLoaderRoute: typeof AdmClientesRouteImport
      parentRoute: typeof AdmRouteRoute
    }
    '/adm/cobranca': {
      id: '/adm/cobranca'
      path: '/cobranca'
      fullPath: '/adm/cobranca'
      preLoaderRoute: typeof AdmCobrancaRouteImport
      parentRoute: typeof AdmRouteRoute
    }
    '/adm/equipe': {
      id: '/adm/equipe'
      path: '/equipe'
      fullPath: '/adm/equipe'
      preLoaderRoute: typeof AdmEquipeRouteImport
      parentRoute: typeof AdmRouteRoute
    }
    '/adm/login': {
      id: '/adm/login'
      path: '/login'
      fullPath: '/adm/login'
      preLoaderRoute: typeof AdmLoginRouteImport
      parentRoute: typeof AdmRouteRoute
    }
    '/api/cakto-webhook': {
      id: '/api/cakto-webhook'
      path: '/api/cakto-webhook'
      fullPath: '/api/cakto-webhook'
      preLoaderRoute: typeof ApiCaktoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fornecedor/': {
      id: '/fornecedor/'
      path: '/'
      fullPath: '/fornecedor/'
      preLoaderRoute: typeof FornecedorIndexRouteImport
      parentRoute: typeof FornecedorRouteRoute
    }
    '/fornecedor/catalogo': {
      id: '/fornecedor/catalogo'
      path: '/catalogo'
      fullPath: '/fornecedor/catalogo'
      preLoaderRoute: typeof FornecedorCatalogoRouteImport
      parentRoute: typeof FornecedorRouteRoute
    }
    '/fornecedor/conversas': {
      id: '/fornecedor/conversas'
      path: '/conversas'
      fullPath: '/fornecedor/conversas'
      preLoaderRoute: typeof FornecedorConversasRouteImport
      parentRoute: typeof FornecedorRouteRoute
    }
    '/fornecedor/pedidos': {
      id: '/fornecedor/pedidos'
      path: '/pedidos'
      fullPath: '/fornecedor/pedidos'
      preLoaderRoute: typeof FornecedorPedidosRouteImport
      parentRoute: typeof FornecedorRouteRoute
    }
    '/fornecedor/vitrine': {
      id: '/fornecedor/vitrine'
      path: '/vitrine'
      fullPath: '/fornecedor/vitrine'
      preLoaderRoute: typeof FornecedorVitrineRouteImport
      parentRoute: typeof FornecedorRouteRoute
    }
    '/adm/cliente/$id': {
      id: '/adm/cliente/$id'
      path: '/cliente/$id'
      fullPath: '/adm/cliente/$id'
      preLoaderRoute: typeof AdmClienteIdRouteImport
      parentRoute: typeof AdmRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAssinaturaRoute: typeof AuthenticatedAssinaturaRoute
  AuthenticatedComprarRoute: typeof AuthenticatedComprarRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConsultorRoute: typeof AuthenticatedConsultorRoute
  AuthenticatedConversasRoute: typeof AuthenticatedConversasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFornecedoresRoute: typeof AuthenticatedFornecedoresRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPdvRoute: typeof AuthenticatedPdvRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAssinaturaRoute: AuthenticatedAssinaturaRoute,
  AuthenticatedComprarRoute: AuthenticatedComprarRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConsultorRoute: AuthenticatedConsultorRoute,
  AuthenticatedConversasRoute: AuthenticatedConversasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFornecedoresRoute: AuthenticatedFornecedoresRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPdvRoute: AuthenticatedPdvRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdmRouteRouteChildren {
  AdmAuditoriaRoute: typeof AdmAuditoriaRoute
  AdmClientesRoute: typeof AdmClientesRoute
  AdmCobrancaRoute: typeof AdmCobrancaRoute
  AdmEquipeRoute: typeof AdmEquipeRoute
  AdmLoginRoute: typeof AdmLoginRoute
  AdmIndexRoute: typeof AdmIndexRoute
  AdmClienteIdRoute: typeof AdmClienteIdRoute
}

const AdmRouteRouteChildren: AdmRouteRouteChildren = {
  AdmAuditoriaRoute: AdmAuditoriaRoute,
  AdmClientesRoute: AdmClientesRoute,
  AdmCobrancaRoute: AdmCobrancaRoute,
  AdmEquipeRoute: AdmEquipeRoute,
  AdmLoginRoute: AdmLoginRoute,
  AdmIndexRoute: AdmIndexRoute,
  AdmClienteIdRoute: AdmClienteIdRoute,
}

const AdmRouteRouteWithChildren = AdmRouteRoute._addFileChildren(
  AdmRouteRouteChildren,
)

interface FornecedorRouteRouteChildren {
  FornecedorCatalogoRoute: typeof FornecedorCatalogoRoute
  FornecedorConversasRoute: typeof FornecedorConversasRoute
  FornecedorPedidosRoute: typeof FornecedorPedidosRoute
  FornecedorVitrineRoute: typeof FornecedorVitrineRoute
  FornecedorIndexRoute: typeof FornecedorIndexRoute
}

const FornecedorRouteRouteChildren: FornecedorRouteRouteChildren = {
  FornecedorCatalogoRoute: FornecedorCatalogoRoute,
  FornecedorConversasRoute: FornecedorConversasRoute,
  FornecedorPedidosRoute: FornecedorPedidosRoute,
  FornecedorVitrineRoute: FornecedorVitrineRoute,
  FornecedorIndexRoute: FornecedorIndexRoute,
}

const FornecedorRouteRouteWithChildren = FornecedorRouteRoute._addFileChildren(
  FornecedorRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdmRouteRoute: AdmRouteRouteWithChildren,
  FornecedorRouteRoute: FornecedorRouteRouteWithChildren,
  CadastroRoute: CadastroRoute,
  ContatoRoute: ContatoRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SobreRoute: SobreRoute,
  TermosRoute: TermosRoute,
  ApiCaktoWebhookRoute: ApiCaktoWebhookRoute,
  ApiHealthRoute: ApiHealthRoute,
  ConviteTokenRoute: ConviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
